const os = require("os");
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const DISCOVERY_MARKER = path.join(__dirname, "../data/.discovery-complete");

function hasTool(name) {
    try {
        execSync(`which ${name} 2>/dev/null`, { stdio: "pipe", timeout: 3000 });
        return true;
    } catch { return false; }
}

function getShell() {
    return process.env.SHELL || os.userInfo().shell || "/bin/bash";
}

function detectLLMProviders() {
    const providers = [];
    const envPath = path.join(__dirname, "../.env");
    let existingEnv = "";
    try { existingEnv = fs.readFileSync(envPath, "utf8"); } catch {}

    const ollamaRunning = hasTool("ollama") && (() => {
        try {
            const out = execSync("ollama list 2>/dev/null", { stdio: "pipe", timeout: 3000 });
            return out.toString().trim().length > 0;
        } catch { return false; }
    })();

    if (ollamaRunning) {
        providers.push({
            name: "Ollama",
            provider: "ollama",
            detected: true,
            envVar: "JARVIS_LLM_PROVIDER=ollama",
            note: "Ollama running — set as default LLM provider"
        });
    }

    const hasOpenAI = !!(process.env.OPENAI_API_KEY || existingEnv.includes("OPENAI_API_KEY="));
    if (hasOpenAI) {
        providers.push({
            name: "OpenAI",
            provider: "openai",
            detected: true,
            envVar: "JARVIS_LLM_PROVIDER=openai",
            note: "OPENAI_API_KEY found"
        });
    }

    const hasGemini = !!(process.env.GEMINI_API_KEY || existingEnv.includes("GEMINI_API_KEY="));
    if (hasGemini) {
        providers.push({
            name: "Gemini",
            provider: "gemini",
            detected: true,
            envVar: "JARVIS_LLM_PROVIDER=gemini",
            note: "GEMINI_API_KEY found"
        });
    }

    return providers;
}

function scanHomeDirectory() {
    const home = os.homedir();
    const patterns = [];
    try {
        const entries = fs.readdirSync(home, { withFileTypes: true });
        const dirs = entries.filter(e => e.isDirectory()).map(e => e.name);

        if (dirs.some(d => /desktop/i.test(d))) patterns.push("desktop");
        if (dirs.some(d => /documents/i.test(d))) patterns.push("documents");
        if (dirs.some(d => /projects/i.test(d))) patterns.push("projects");
        if (dirs.some(d => /code/i.test(d))) patterns.push("code");
        if (dirs.some(d => /business/i.test(d))) patterns.push("business");
        if (dirs.some(d => /clients/i.test(d))) patterns.push("clients");

        const hasPackageJson = fs.existsSync(path.join(home, "package.json"));
        const hasGitConfig = fs.existsSync(path.join(home, ".gitconfig"));
        if (hasPackageJson || hasGitConfig) patterns.push("developer");

        if (fs.existsSync(path.join(home, "Google Drive")) || fs.existsSync(path.join(home, "Dropbox"))) {
            patterns.push("cloud-storage");
        }
    } catch {}

    return {
        homeDir: home,
        patterns,
        desktop: fs.existsSync(path.join(home, "Desktop")),
        documents: fs.existsSync(path.join(home, "Documents")),
        downloads: fs.existsSync(path.join(home, "Downloads"))
    };
}

function scanSoftware() {
    const tools = {};
    const checks = [
        "node", "npm", "npx", "git", "docker", "code", "cursor",
        "ollama", "python3", "python", "java", "go", "rustc", "cargo",
        "brew", "make", "gcc", "clang", "ngrok", "cloudflared",
        "tailscale", "psql", "mysql", "redis-cli", "ffmpeg"
    ];
    for (const tool of checks) {
        tools[tool] = hasTool(tool);
    }
    return tools;
}

function generateEnvTemplate(discovery) {
    const lines = [
        "# JARVIS OS Environment Configuration",
        "# Auto-generated by Discovery Agent",
        `# Generated: ${new Date().toISOString()}`,
        `# OS: ${discovery.system.os} ${discovery.system.release}`,
        `# Node: ${discovery.system.nodeVersion}`,
        "",
        "# LLM Provider — choose one: ollama, openai, gemini, groq, or leave blank for rule-based only",
        `JARVIS_LLM_PROVIDER=${discovery.llm.length > 0 ? discovery.llm[0].provider : "ollama"}`,
        "",
        "# API Keys (add your own)",
        "# OPENAI_API_KEY=sk-...",
        "# GEMINI_API_KEY=...",
        "# GROQ_API_KEY=...",
        "",
        "# Network",
        "JARVIS_HOST=127.0.0.1",
        "# JARVIS_ALLOWED_HOSTS=your-local-ip",
        "",
        "# Auth Tokens (auto-generated on first start)",
        "# JARVIS_OWNER_TOKEN=...",
        "# JARVIS_OPERATOR_TOKEN=...",
        "# JARVIS_VIEWER_TOKEN=...",
        "",
        "# Email (optional — for outreach campaigns)",
        "# SMTP_HOST=smtp.gmail.com",
        "# SMTP_PORT=587",
        "# SMTP_USER=your@email.com",
        "# SMTP_PASS=your-app-password",
        "# SMTP_FROM=Your Name <your@email.com>",
        "",
        "# Lemon Squeezy (optional — for selling JARVIS templates/products)",
        "# LEMON_SQUEEZY_API_KEY=...",
        "# LEMON_SQUEEZY_STORE_ID=...",
        "# LEMON_SQUEEZY_WEBHOOK_SECRET=...",
        ""
    ];

    if (discovery.llm.length > 0) {
        lines.push(`# Detected: ${discovery.llm.map(p => p.name).join(", ")}`);
        for (const p of discovery.llm) {
            lines.push(`# ${p.note}`);
        }
    } else {
        lines.push("# No LLM providers detected locally.");
        lines.push("# JARVIS runs in rule-based mode without an LLM.");
        lines.push("# Add an API key above to enable AI features.");
    }

    return lines.join("\n") + "\n";
}

function runDiscovery() {
    if (fs.existsSync(DISCOVERY_MARKER)) {
        const cached = JSON.parse(fs.readFileSync(DISCOVERY_MARKER, "utf8"));
        return { ...cached, cached: true };
    }

    const discovery = {
        system: {
            os: os.platform(),
            release: os.release(),
            arch: os.arch(),
            hostname: os.hostname(),
            nodeVersion: process.version,
            cpus: os.cpus().length,
            memory: `${Math.round(os.totalmem() / 1024 / 1024 / 1024)}GB`,
            shell: getShell()
        },
        home: scanHomeDirectory(),
        tools: scanSoftware(),
        llm: detectLLMProviders(),
        performedAt: new Date().toISOString()
    };

    try {
        fs.mkdirSync(path.dirname(DISCOVERY_MARKER), { recursive: true });
        fs.writeFileSync(DISCOVERY_MARKER, JSON.stringify(discovery, null, 2));
    } catch {}

    return { ...discovery, cached: false };
}

function generateEnv() {
    const discovery = runDiscovery();
    const envPath = path.join(__dirname, "../.env");

    if (fs.existsSync(envPath)) {
        return { exists: true, path: envPath };
    }

    const content = generateEnvTemplate(discovery);
    fs.writeFileSync(envPath, content);
    return { exists: false, created: true, path: envPath, content };
}

function getSummary(discovery) {
    const s = discovery.system;
    const home = discovery.home;
    const tools = discovery.tools;

    const available = Object.entries(tools).filter(([,v]) => v).map(([k]) => k);
    const missing = Object.entries(tools).filter(([,v]) => !v).map(([k]) => k);

    return {
        title: "JARVIS OS Discovery Complete",
        environment: `${s.os} ${s.release} · ${s.nodeVersion} · ${s.cpus} cores · ${s.memory} RAM`,
        toolsFound: available.length,
        toolsList: available,
        toolsMissing: missing.filter(t => ["docker", "ollama", "git", "python3", "code"].includes(t)),
        homePatterns: home.patterns,
        llmProviders: discovery.llm.map(p => p.name),
        llmAutoConfigured: discovery.llm.length > 0
    };
}

module.exports = { runDiscovery, generateEnv, getSummary, hasTool, scanSoftware, scanHomeDirectory };
