(function () {
    const escapeHtml = value => { const node = document.createElement("div"); node.textContent = String(value ?? ""); return node.innerHTML; };
    async function request(url, options) { const response = await fetch(url, options); const payload = await response.json(); if (!response.ok || !payload.ok) throw new Error(payload.error?.message || payload.error || "Request failed"); return payload.data; }
    function render(workspace, data, notice = "") {
        const agent = data.agents[0]; const schedule = data.schedules[0];
        workspace.innerHTML = `<section class="production-agents">
            <header><div><div class="eyebrow">JARVIS OS / PRODUCTION AGENTS</div><h1>Supervised Agent Operations</h1><p>Typed services, approved connectors, durable schedules, and traceable run history.</p></div><span>${escapeHtml(agent.mode)}</span></header>
            ${notice ? `<div class="agent-notice">${escapeHtml(notice)}</div>` : ""}
            <div class="agent-metrics"><article><small>AGENTS</small><strong>${data.agents.length}</strong></article><article><small>RUNS</small><strong>${data.metrics.runs}</strong></article><article><small>PREPARED</small><strong>${data.metrics.prepared}</strong></article><article><small>EXTERNAL ACTIONS</small><strong>${data.metrics.externalActions}</strong></article></div>
            <article class="agent-panel"><div><div class="eyebrow">ACTIVE SERVICE</div><h2>${escapeHtml(agent.name)} <small>v${escapeHtml(agent.version)}</small></h2><p>${agent.capabilities.map(escapeHtml).join(" · ")}</p></div><strong>${escapeHtml(agent.workflow)}</strong></article>
            <article class="agent-panel"><div><div class="eyebrow">DURABLE SCHEDULE</div><h2>${escapeHtml(schedule.frequency)} renewal review</h2><p>${schedule.enabled ? "Enabled for manually authorized supervised runs." : "Disabled until the owner explicitly enables it."} Background execution remains off.</p></div><button id="toggleAgentSchedule">${schedule.enabled ? "DISABLE" : "ENABLE"} SCHEDULE</button></article>
            <article class="agent-panel connectors"><div class="eyebrow">CONNECTORS</div>${data.connectors.map(item => `<p><strong>${escapeHtml(item.id)}</strong><span>${item.approved ? "APPROVED" : "DISABLED"} · ${escapeHtml(item.access)} · ${escapeHtml(item.freshness)}</span></p>`).join("")}</article>
            <article class="agent-panel history"><div class="eyebrow">SUPERVISED RUN HISTORY</div>${data.recentRuns.length ? data.recentRuns.map(item => `<p><strong>${escapeHtml(item.outcome)}</strong><span>${escapeHtml(item.completedAt)} · ${escapeHtml(item.preparedCount)} prepared · trace ${escapeHtml(item.traceId)}</span></p>`).join("") : "<p>No supervised runs recorded.</p>"}<button id="runProductionAgent" ${schedule.enabled ? "" : "disabled"}>RUN SUPERVISED REVIEW</button></article>
            <p class="agent-boundary">No background execution, outreach, CRM mutation, spending, publishing, contracts, or transactions. Owner enables schedules; an authenticated operator starts each run.</p>
        </section>`;
        document.getElementById("toggleAgentSchedule")?.addEventListener("click", async () => { try { await request(`/api/production-agents/schedules/${schedule.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: !schedule.enabled, confirmation: schedule.enabled ? "DISABLE SCHEDULE" : "ENABLE SCHEDULE" }) }); render(workspace, await request("/api/production-agents/status"), `Schedule ${schedule.enabled ? "disabled" : "enabled"}.`); } catch (error) { render(workspace, data, `Connect as owner to change the schedule: ${error.message}`); } });
        document.getElementById("runProductionAgent")?.addEventListener("click", async () => { try { const run = await request("/api/production-agents/runs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ scheduleId: schedule.id, confirmation: "RUN SUPERVISED" }) }); render(workspace, await request("/api/production-agents/status"), `Supervised run complete: ${run.outcome}.`); } catch (error) { render(workspace, data, `Run blocked: ${error.message}`); } });
    }
    async function loadProductionAgents() { const workspace = document.getElementById("conversation"); workspace.innerHTML = `<section class="production-agents"><article class="agent-panel">Loading production agents...</article></section>`; try { render(workspace, await request("/api/production-agents/status")); } catch (error) { workspace.innerHTML = `<section class="production-agents"><article class="agent-panel">${escapeHtml(error.message)}</article></section>`; } }
    window.loadProductionAgents = loadProductionAgents;
}());
